-- DAY 2: 

-- TO CREATE A TABLE:

-- Creating a Table: 

CREATE TABLE IF NOT EXISTS users (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    GENDER ENUM('MALE', 'FEMALE', 'NOGENDER') NOT NULL,
    DATE_OF_BIRTH DATE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DESCRIBE users;
