-- DAY 2: 

-- TO CREATE A TABLE:

-- Creating a Table: 

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    gender ENUM('MALE', 'FEMALE', 'NOGENDER') NOT NULL,
    date_of_birth DATE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

SELECT * FROM users;

DESCRIBE users; 



